### ISSUE TITLE
Base images where package should be pip installable

### ISSUE THREAD

**Issue by eho-tacc** [TACC-Cloud/python-reactors#10]
`python-reactors` should be pip installable, and preferably passing minimal pytests, in each of the following base images. In addition, `python -m reactors.cli usage` should exit 0 for each environment.

## Minimal

* [x] `python:3.6-alpine`
    * Passing for [hello_world reactor `8871e787c275c631f9e3935b89e236e0d311d809`](https://github.com/TACC-Cloud/example-reactors/tree/8871e787c275c631f9e3935b89e236e0d311d809) 
* [x] `python:3.7-alpine`
    * Passing for [hello_world reactor `322983c81a0e437651df9a041ce4fb1f8c0d2394`](https://github.com/TACC-Cloud/example-reactors/tree/322983c81a0e437651df9a041ce4fb1f8c0d2394)
* `python:alpine`
* [X] `ubuntu:20.04`
    * Passing for [hello_world reactor `0ffd4bf98b824cc8790d322c5ef3923ec298acd3`](https://github.com/TACC-Cloud/example-reactors/tree/0ffd4bf98b824cc8790d322c5ef3923ec298acd3)
* [ ] ~~`ubuntu:18.04`~~
    * Absurdly difficult to install a version of Python other than 3.6.9 with pip in 18.04
    * And one of our dependencies has a [3.6.9 incompatibility](https://github.com/dustinkirkland/python-petname/issues/11)
    * Documented on #12 
* [x] `continuumio/miniconda3:4.7.12-alpine`
    * Passing for [hello_world reactor `e294ad2a51eb06480837c78b2059d193694b7ce3`](https://github.com/TACC-Cloud/example-reactors/tree/e294ad2a51eb06480837c78b2059d193694b7ce3)

**Comment by eho-tacc** [comment]
## Existing Reactors

* [TACC-Cloud/example-reactors](https://github.com/TACC-Cloud/example-reactors)

**Comment by shwetagopaul92** [comment]
- [ ] sd2e/python3:ubuntu17
- [ ] sd2e/reactors:python3

**Comment by shwetagopaul92** [comment]
Test cases: 

Test against python-reactors: 

- [ ] Data converge reactor

**Comment by eho-tacc** [comment]
#14 builds `tacc/reactors:python3` from the `python:*-buster` images
