### ISSUE TITLE
Broken petname dependency installation

### ISSUE THREAD

**Issue by eho-tacc** [TACC-Cloud/python-reactors#12]
- Test env
    - `ubuntu:18.04` Docker image
    - Python 3.6.9
    - `pip3 install petname`
- Culprit was README reading in `setup.py` that threw a `UnicodeDecodeError`
- Installation error propagates when pip installing python-reactors
- Submitted [PR](https://github.com/dustinkirkland/python-petname/pull/12) on `petname`

**Comment by ethho** [comment]
Specific to Ubuntu locale issues.
