### ISSUE TITLE
x-nonce and CLI credentials are not redacted

### ISSUE THREAD

**Issue by eho-tacc** [TACC-Cloud/python-reactors#34]
The following pytest(s) checks for attributes in the `Reactor.context` that should be redacted regardless of their value or the `Reactor.redact` setting: https://github.com/TACC-Cloud/python-reactors/blob/caa7816e91bf1cd72e8fad8da33ce56437ca6939/tests/test_logs.py#L82-L87

Currently both are printing value to stdout, and thus failing both pytests as of caa7816.

**Comment by eho-tacc** [comment]
`x-nonce` *should* have been redacted by value in https://github.com/TACC-Cloud/python-reactors/blob/caa7816e91bf1cd72e8fad8da33ce56437ca6939/src/reactors/config.py#L104-L104

**Comment by eho-tacc** [comment]
## Quick-Start

```bash
git checkout 34-redact
tox -- tests/test_logs.py
```

**Comment by ethho** [comment]
Working branch is `34-eho-dev`
